# timeout
timeout = "1200s"
# your website url
baseURL = 'https://example.org/'
# website title
title = 'public class lambdaCatfishPhotos {'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

# theme as module
[module]
replacements = "github.com/Sped0n/bridget/v2 -> /Users/Jack/Projects/photography-site/themes/bridget"
[[module.imports]]
path = "github.com/Sped0n/bridget/v2"
